version: '3.9'

services:
  database:
    image: mysql
    platform: linux/x86_64
    container_name: costs
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'costs'
    ports:
      - '3308:3306'